### ISSUE TITLE
Add support for the whole Debian and RedHat families

### ISSUE THREAD

**Issue by asghaier** [kbrebanov/ansible-selinux#2]
The current Ansible role works only with CentOS and Ubuntu. This role should be compatible with the whole Debian and RedHat family and should work with other similar distributions.

**Comment by asghaier** [comment]
@kbrebanov can you please have a look on PR #3 ?
I need this for the playbook to work with RHEL7.
I have tested this and it works like a charm with RHEL7 with those changes.

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
